### ISSUE TITLE
Document backend environment variables in a Google Doc

### ISSUE THREAD

**Issue by altry104** [projectdim/backend#10]
We should attempt to document each of the backend environment variables (in a separate document) so that other project members will have a sense for what some of them actually do.

Please consider removing unused environment variables as well.

**Comment by altry104** [comment]
Hey everyone, please use [this link](https://docs.google.com/document/d/1WYOekDzkeJMZWU1p4ANOWbwgihbEUznk7n5YWb4QNI8/edit) for the current documentation concerning the backend variables.

This will be updated frequently in the upcoming weeks, so I will be in touch.

As well, all of the listed env variables have their default values specified in the app's config file, you might want to look at it too.

For dev, please be sure that your **ENV_TYPE** is set to "test" and **EMAILS_ENABLED** is set to False.

**Comment by philipkoshy** [comment]
It looks like access to the Google Doc is restricted - I need to request permission to view the doc. I would open up the permissions to everyone since there shouldn't be anything sensitive in this doc (I hope).

**Comment by altry104** [comment]
Yup, fixed that.
